In [ ]:
from google.colab import files
files.upload()

Saving weather.nominal.csv to weather.nominal.csv

{'weather.nominal.csv': b'outlook,temperature,humidity,windy,play\r\nsunny,hot,high,FALSE,no\r\nsunny,hot,high,TRUE,no\r\novercast,hot,high,FALSE,yes\r\nrainy,mild,high,FALSE,yes\r\nrainy,cool,normal,FALSE,yes\r\nrainy,cool,normal,TRUE,no\r\novercast,cool,normal,TRUE,yes\r\nsunny,mild,high,FALSE,no\r\nsunny,cool,normal,FALSE,yes\r\nrainy,mild,normal,FALSE,yes\r\nsunny,mild,normal,TRUE,yes\r\novercast,mild,high,TRUE,yes\r\novercast,hot,normal,FALSE,yes\r\nrainy,mild,high,TRUE,no\r\n'}

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv("weather.nominal.csv")

In [ ]:
data

     outlook temperature humidity  windy play
0      sunny         hot     high  False   no
1      sunny         hot     high   True   no
2   overcast         hot     high  False  yes
3      rainy        mild     high  False  yes
4      rainy        cool   normal  False  yes
5      rainy        cool   normal   True   no
6   overcast        cool   normal   True  yes
7      sunny        mild     high  False   no
8      sunny        cool   normal  False  yes
9      rainy        mild   normal  False  yes
10     sunny        mild   normal   True  yes
11  overcast        mild     high   True  yes
12  overcast         hot   normal  False  yes
13     rainy        mild     high   True   no

In [ ]:
x = data[['outlook','temperature','humidity','windy']] #features
y = data['play'] #target

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 0)

In [ ]:
x_train

     outlook temperature humidity  windy
13     rainy        mild     high   True
9      rainy        mild   normal  False
1      sunny         hot     high   True
7      sunny        mild     high  False
10     sunny        mild   normal   True
3      rainy        mild     high  False
0      sunny         hot     high  False
5      rainy        cool   normal   True
12  overcast         hot   normal  False

In [ ]:
x_test

     outlook temperature humidity  windy
8      sunny        cool   normal  False
6   overcast        cool   normal   True
4      rainy        cool   normal  False
11  overcast        mild     high   True
2   overcast         hot     high  False

In [ ]:
y_train

13     no
9     yes
1      no
7      no
10    yes
3     yes
0      no
5      no
12    yes
Name: play, dtype: object

In [ ]:
y_test

8     yes
6     yes
4     yes
11    yes
2     yes
Name: play, dtype: object

In [ ]:
pd.get_dummies(data)

,windy,outlook_overcast,outlook_rainy,outlook_sunny,temperature_cool,temperature_hot,temperature_mild,humidity_high,humidity_normal,play_no,play_yes
0,False,0,0,1,0,1,0,1,0,1,0
1,True,0,0,1,0,1,0,1,0,1,0
2,False,1,0,0,0,1,0,1,0,0,1
3,False,0,1,0,0,0,1,1,0,0,1
4,False,0,1,0,1,0,0,0,1,0,1
5,True,0,1,0,1,0,0,0,1,1,0
6,True,1,0,0,1,0,0,0,1,0,1
7,False,0,0,1,0,0,1,1,0,1,0
8,False,0,0,1,1,0,0,0,1,0,1
9,False,0,1,0,0,0,1,0,1,0,1
10,True,0,0,1,0,0,1,0,1,0,1
11,True,1,0,0,0,0,1,1,0,0,1
12,False,1,0,0,0,1,0,0,1,0,1
13,True,0,1,0,0,0,1,1,0,1,0